apiVersion: v1
kind: Service
metadata:
  name: k8s-external-kafka-service
spec:
  ports:
    - port: 9092

---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-external-kafka-service
subsets:
  - addresses:
      - ip: 172.30.1.29
    ports:
      - port: 9092
